### ISSUE TITLE
About this project for china stock market 

### ISSUE THREAD

**Issue by nkta3m** [gaborvecsei/Stocks-Pattern-Analyzer#11]
Hello，guys
Thank you very much for this project, I have 2 questions:
1. What is the purpose of the s&p list? If I were to target the Chinese stock market, should this section be replaced by a Chinese version of the list?
2. Symblos can set my own list individually, do I still need the list mentioned above?

**Comment by gaborvecsei** [comment]
The S&P500 list (https://github.com/gaborvecsei/Stocks-Pattern-Analyzer/blob/master/rest_api.py#L35) is there just to retrieve the tickers in the list. This way we have access to all of those companies and we don't need to define them manually.

If you'd like to include other symbols as well use the `symbols.txt` as stated here: https://github.com/gaborvecsei/Stocks-Pattern-Analyzer#run-it-locally or you can edit the code

**Comment by nkta3m** [comment]
Thanks for the reply, I have switched to the Chinese list and stock symbols. thank you.

**Comment by gaborvecsei** [comment]
Nice! You are welcome
