### ISSUE TITLE
About patterns to match.

### ISSUE THREAD

**Issue by nkta3m** [gaborvecsei/Stocks-Pattern-Analyzer#12]
Hello guys
I still have a question to ask:
Is there a relationship with Patterns to match (MAX: 10) and this picture below? This value is predicted in the order of this picture? Or is it predicted? Is it possible to predict according to a patterns?

![Trading-Patterns-Cheat-Sheet](https://user-images.githubusercontent.com/13484700/148344872-61080ed9-9c48-42f2-9ed4-5710a97694c8.jpg)

**Comment by gaborvecsei** [comment]
There is no connection with these patterns in the repo. This is just an illustrative image on what might you come across when studying the patterns 
You can read about it here: https://www.gaborvecsei.com/Stock-Pattern-Analyzer/
