### ISSUE TITLE
Add a virtual environment package like Poetry to support off-docker development

### ISSUE THREAD

**Issue by gurashish1singh** [gaborvecsei/Stocks-Pattern-Analyzer#3]
The current setup of the app can either run in docker or Heroku without much issues. But if i want to run the app outside docker using "python rest_api.py" and "python dash_app.py" I have to install all the pip requirements to my own virtual env. If we add poetry as a virtual environment it might things more easy and streamlined. Thoughts?

**Comment by gaborvecsei** [comment]
Thanks for the suggestion but I don't think this is necessary as the `requirements.txt` and the docker image convers all use cases
