### ISSUE TITLE
Docker container doesn't stop automatically after we exit the container

### ISSUE THREAD

**Issue by gurashish1singh** [gaborvecsei/Stocks-Pattern-Analyzer#4]
After standing up the container using "$ docker run --rm --name stock -v $(pwd):/code -p 8050:8050 stock start.sh" and then pressing "ctrl + c" to exit out of the environment, the app still runs in the background. Is this the intended behavior?

**Comment by gaborvecsei** [comment]
The `--rm` should remove the container. If this does not work for you please, check your docker config/setup.

You can stop it with `docker kill stock`

**Comment by gurashish1singh** [comment]
I don't think its wise that people should edit their docker config/setup files. Maybe we should think of creating a bash script which stands up the container and then waits for user input to exit(should be a pretty easy bash script to create).

**Comment by gaborvecsei** [comment]
What I meant by that is that probably your setup is not correct. As you can see with `--rm` this should be automatic: https://docs.docker.com/engine/reference/run/#clean-up---rm
