### ISSUE TITLE
Run with a single script option mentioned in the readme doesn't work

### ISSUE THREAD

**Issue by gurashish1singh** [gaborvecsei/Stocks-Pattern-Analyzer#5]
Since the bash script has the command "python /code/rest_api.py &"  which I assume is primarily for running in the container, on local the command errors out since nothing has been copied over to /code.

**Comment by gaborvecsei** [comment]
The `start.sh` shouold be used only with docker. It is not intended to work outside. Just use `python`

**Comment by gurashish1singh** [comment]
![image](https://user-images.githubusercontent.com/51451177/111996732-b34ec480-8af0-11eb-9162-1e8607816114.png)

Your readme mentions this. So this command doesn't work stand-alone. Maybe you should update the Readme as this is a bit misleading.
