### ISSUE TITLE
[Question] How do you refresh data_holder online

### ISSUE THREAD

**Issue by QiXuanWang** [gaborvecsei/Stocks-Pattern-Analyzer#8]
I'm now able to run this app and it works alright. One question is that when I download data everyday into local disk, how can I let rest_api to automatically refresh data? 
Is there a plan to do so if not implemented yet?

BTW, why react? anything wrong with dash app?

**Comment by gaborvecsei** [comment]
I am not planning to include this, but it is super easy to include. You just need and endpoint which adds a symbol to the `SYMBOL_LIST` and then calls the `refresh` endpoint.

> BTW, why react? anything wrong with dash app?

Harder to maintain and not a good fit for production (in my opinion). It is solving the problem with the wrong tool. But great for simple and quick dashboards like what I did.
